/// name_convert(number)
// Converts keycode to text to make it readable for people.

    switch(argument0)
    {
        case 38:
            return "UP";
        case 40:
            return "DOWN";
        case 37:
            return "LEFT";
        case 39:
            return "RIGHT";
        case 65:
            return "A";
        case 90:
            return "Z";
        case 69:
            return "E";
        case 82:
            return "R";
        case 84:
            return "T";
        case 89:
            return "Y";
        case 85:
            return "U";
        case 73:
            return "I";
        case 79:
            return "O";
        case 80:
            return "P";
        case 81:
            return "Q";
        case 83:
            return "S";
        case 68:
            return "D";
        case 70:
            return "F";
        case 71:
            return "G";
        case 72:
            return "H";
        case 74:
            return "J";
        case 75:
            return "K";
        case 76:
            return "L";
        case 77:
            return "M";
        case 87:
            return "W";
        case 88:
            return "X";
        case 67:
            return "C";
        case 86:
            return "V";
        case 66:
            return "B";
        case 78:
            return "N";
        case 32:
            return "SpaceB";
        case 13:
            return "Enter";
        case 8:
            return "BackS";
        case 160:
            return "LShift";
        case 161:
            return "RShift";
        default:
            return "?";
    }
